package ru.teacherstaff.adaptive;

import jakarta.servlet.http.*;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.web.bind.annotation.*;
import org.springframework.transaction.annotation.Transactional;
import java.security.SecureRandom;
import java.time.*;
import java.util.*;

@RestController @RequestMapping("/api")
public class ApiController {
  private final JdbcTemplate db; private final PistonCodeRunner codeRunner; private final LlmTutor tutor; private final LearningContentGenerator contentGenerator; private final BCryptPasswordEncoder passwords=new BCryptPasswordEncoder();
  @Value("${app.session-hours}") long sessionHours; @Value("${app.cookie-secure}") boolean secureCookie; @Value("${app.piston.base-url}") String pistonUrl;
  ApiController(JdbcTemplate db, PistonCodeRunner codeRunner, LlmTutor tutor, LearningContentGenerator contentGenerator) { this.db=db; this.codeRunner=codeRunner; this.tutor=tutor; this.contentGenerator=contentGenerator; }
  @PostMapping("/auth/login") public Map<String,Object> login(@RequestBody Map<String,String> body, HttpServletResponse response) {
    var rows=db.queryForList("select id,login,password_hash,role,display_name,llm_enabled from users where login=?",body.get("login"));
    if(rows.isEmpty() || !passwords.matches(body.getOrDefault("password",""),(String)rows.getFirst().get("password_hash"))) throw bad("INVALID_CREDENTIALS","Неверный логин или пароль");
    var u=rows.getFirst(); String token=randomToken(); db.update("insert into sessions(token_hash,user_id,expires_at) values(?,?,?)",Hashing.sha256(token),u.get("id"),Instant.now().plus(Duration.ofHours(sessionHours)).toString());
    Cookie c=new Cookie("adaptive_session",token); c.setHttpOnly(true); c.setPath("/api"); c.setMaxAge((int)Duration.ofHours(sessionHours).toSeconds()); c.setSecure(secureCookie); response.addCookie(c); return status(u);
  }
  @PostMapping("/auth/logout") @ResponseStatus(HttpStatus.NO_CONTENT) public void logout(HttpServletRequest r,HttpServletResponse p) { cookie(r).ifPresent(t->db.update("delete from sessions where token_hash=?",Hashing.sha256(t))); Cookie c=new Cookie("adaptive_session","");c.setPath("/api");c.setMaxAge(0);p.addCookie(c); }
  @GetMapping("/auth/me") public Map<String,Object> me(HttpServletRequest r) { return status(user(r)); }

  @GetMapping("/diagnostic") public Map<String,Object> diagnostic(HttpServletRequest r) { long id=uid(r); boolean done=count("select count(*) from student_languages where user_id=? and diagnostic_completed_at is not null",id)>0; var qs=db.queryForList("select id,ordinal,skill_code,prompt,options_json from diagnostic_questions order by ordinal"); return Map.of("completed",done,"questions",done?List.of():qs.stream().map(q->Map.of("id",q.get("id"),"ordinal",q.get("ordinal"),"skillCode",q.get("skill_code"),"prompt",q.get("prompt"),"options",json(q.get("options_json")),"unknownOption",Map.of("label","Не знаю"))).toList()); }
  @PostMapping("/diagnostic") @Transactional public Map<String,Object> submitDiagnostic(@RequestBody Map<String,Object> body,HttpServletRequest r) { long user=student(r); if(count("select count(*) from student_languages where user_id=? and diagnostic_completed_at is not null",user)>0) throw bad("DIAGNOSTIC_ALREADY_COMPLETED","Диагностика уже пройдена");
    @SuppressWarnings("unchecked") List<Map<String,Object>> answers=(List<Map<String,Object>>)body.get("answers"); if(answers==null || answers.size()!=count("select count(*) from diagnostic_questions")) throw bad("INVALID_DIAGNOSTIC","Нужны ответы на все вопросы");
    Map<Long,Integer> received=new HashMap<>(); for(var a:answers) { long id=((Number)a.get("questionId")).longValue(); Integer choice=a.get("selectedOption")==null?null:((Number)a.get("selectedOption")).intValue(); if(choice!=null&&(choice<0||choice>3)||received.containsKey(id)) throw bad("INVALID_DIAGNOSTIC","Ответы должны быть уникальны и иметь допустимый вариант"); received.put(id,choice); }
    var qs=db.queryForList("select id,correct_option,block_no from diagnostic_questions"); Map<Integer,int[]> score=new HashMap<>(); for(var q:qs){long qid=((Number)q.get("id")).longValue(); Integer selected=received.get(qid); if(!received.containsKey(qid))throw bad("INVALID_DIAGNOSTIC","Есть неизвестный вопрос"); boolean ok=selected!=null&&selected.equals(((Number)q.get("correct_option")).intValue()); db.update("insert into diagnostic_answers(user_id,question_id,selected_option,is_correct) values(?,?,?,?)",user,qid,selected,ok?1:0); int[] s=score.computeIfAbsent(((Number)q.get("block_no")).intValue(),x->new int[2]);s[1]++;if(ok)s[0]++;}
    int start=score.keySet().stream().sorted().filter(b->score.get(b)[0]*100<score.get(b)[1]*80).findFirst().orElse(score.keySet().stream().max(Integer::compare).orElse(0)); db.update("insert into student_languages(user_id,diagnostic_completed_at,starting_block) values(?,?,?)",user,Instant.now().toString(),start); return Map.of("completed",true,"startingBlock",start); }

  @GetMapping("/lessons/current") public Map<String,Object> current(HttpServletRequest r){return obj("lesson",active(uid(r)));}
  @PostMapping("/lessons/start") public Map<String,Object> start(HttpServletRequest r){long u=student(r);requireDiagnostic(u);var current=active(u);if(current!=null)return Map.of("lesson",current);int n=count("select count(*) from lessons where user_id=?",u)+1;db.update("insert into lessons(user_id,lesson_number) values(?,?)",u,n);return Map.of("lesson",active(u));}
  @PostMapping("/lessons/{id}/finish") public Map<String,Object> finish(@PathVariable long id,HttpServletRequest r){long u=student(r);if(db.update("update lessons set finished_at=? where id=? and user_id=? and finished_at is null",Instant.now().toString(),id,u)==0)throw bad("LESSON_NOT_ACTIVE","Активный урок не найден");return Map.of("lesson",lesson(id));}
  @GetMapping("/learning/next") @Transactional public Map<String,Object> next(HttpServletRequest r) {
    long userId=student(r); var lesson=active(userId);
    if(lesson==null) throw bad("NO_ACTIVE_LESSON","Сначала начните урок");
    var assigned=unsolvedTask(lesson);
    if(assigned!=null) return learningResponse(userId,lesson,assigned);
    var skill=nextSkill(userId,((Number)lesson.get("number")).intValue(),((Number)lesson.get("id")).longValue());
    if(skill==null) return obj("lesson",lesson,"skill",null,"explanation",null,"task",null,"reason","NO_DUE_SKILL","llm",llm(userId));
    String skillCode=(String)skill.get("code");
    var explanationRows=db.queryForList("select content,source from explanations where skill_code=?",skillCode);
    Object explanation=explanationRows.isEmpty()?generatedExplanation(userId, skillCode):explanationRows.getFirst();
    var tasks=availableTasks(userId, lesson, skillCode);
    if(tasks.isEmpty()) {
      if(!tutor.status(userId).available()) return obj("lesson",lesson,"skill",skill,"explanation",explanation,"task",null,"reason","NO_TASK_AVAILABLE","llm",llm(userId));
      if(!codeRunner.status().available()) return obj("lesson",lesson,"skill",skill,"explanation",explanation,"task",null,"reason","RUNNER_UNAVAILABLE","llm",llm(userId),"runner",runner());
      boolean stored=false;
      for(int attempt=0;attempt<2&&!stored;attempt++) try { storeGeneratedTask(contentGenerator.generateTask(userId, skillCode)); stored=true; }
      catch (InvalidGeneratedContentException ignored) { }
      catch (LlmUnavailableException e) { return obj("lesson",lesson,"skill",skill,"explanation",explanation,"task",null,"reason","NO_TASK_AVAILABLE","llm",llm(userId)); }
      tasks=availableTasks(userId, lesson, skillCode);
      if(tasks.isEmpty()&&!stored) return obj("lesson",lesson,"skill",skill,"explanation",explanation,"task",null,"reason","LLM_GENERATION_FAILED_VALIDATION","llm",llm(userId));
    }
    if(tasks.isEmpty()) return obj("lesson",lesson,"skill",skill,"explanation",explanation,"task",null,"reason","NO_TASK_AVAILABLE","llm",llm(userId));
    var task=tasks.getFirst(); db.update("insert into lesson_tasks(lesson_id,task_id) values(?,?)",lesson.get("id"),task.get("id"));
    return obj("lesson",lesson,"skill",skill,"explanation",explanation,"task",taskView(task));
  }
  private Map<String,Object> unsolvedTask(Map<String,Object> lesson) { var rows=db.queryForList("select t.id,t.title,t.statement,t.starter_code,ts.skill_code, s.title as skill_title,s.block_no from lesson_tasks lt join tasks t on t.id=lt.task_id join task_target_skills ts on ts.task_id=t.id join skills s on s.code=ts.skill_code where lt.lesson_id=? and not exists(select 1 from submissions x where x.lesson_id=lt.lesson_id and x.task_id=lt.task_id and x.passed=1) order by lt.rowid desc limit 1",lesson.get("id"));return rows.isEmpty()?null:rows.getFirst(); }
  private Map<String,Object> learningResponse(long userId,Map<String,Object> lesson,Map<String,Object> task) { String skillCode=(String)task.get("skill_code");var explanationRows=db.queryForList("select content,source from explanations where skill_code=?",skillCode);Object explanation=explanationRows.isEmpty()?generatedExplanation(userId,skillCode):explanationRows.getFirst();return obj("lesson",lesson,"skill",Map.of("code",skillCode,"title",task.get("skill_title"),"blockNo",task.get("block_no")),"explanation",explanation,"task",taskView(task)); }
  private Map<String,Object> taskView(Map<String,Object> task) { return Map.of("id",task.get("id"),"title",task.get("title"),"statement",task.get("statement"),"starterCode",task.get("starter_code")); }
  private List<Map<String,Object>> availableTasks(long userId,Map<String,Object> lesson,String skillCode) {
    return db.queryForList("select t.id,t.title,t.statement,t.starter_code from tasks t join task_target_skills ts on ts.task_id=t.id where t.active=1 and ts.skill_code=? and not exists(select 1 from successful_task_credit c where c.user_id=? and c.task_id=t.id) and not exists(select 1 from lesson_tasks x where x.lesson_id=? and x.task_id=t.id) and not exists(select 1 from task_prerequisite_skills req where req.task_id=t.id and not exists(select 1 from student_skills p where p.user_id=? and p.skill_code=req.skill_code and p.mastered=1)) order by t.id",skillCode,userId,lesson.get("id"),userId);
  }
  private Object generatedExplanation(long studentId, String skillCode) {
    if(!tutor.status(studentId).available()) return null;
    return contentGenerator.generateExplanation(studentId, skillCode).map(ex -> {
      if(!skillCode.equals(ex.skillCode()) || ex.content()==null || ex.content().isBlank()) throw bad("INVALID_LLM_CONTENT","LLM returned an invalid explanation");
      db.update("insert into explanations(skill_code,content,source) values(?,?,?)",skillCode,ex.content(),"LLM");
      return Map.of("content",ex.content(),"source","LLM");
    }).orElse(null);
  }
  private void storeGeneratedTask(GeneratedTask task) {
    if(task==null || task.skillCode()==null || task.title()==null || task.title().isBlank() || task.statement()==null || task.statement().isBlank() || task.testSource()==null || task.testSource().isBlank() || !task.testSource().contains("class TestHarness") || !task.testSource().contains("main(") || !task.testSource().contains(PistonCodeRunner.PASS_MARKER_PLACEHOLDER) || task.testFileName()==null || task.testFileName().isBlank() || task.referenceSolutionSource()==null || task.referenceSolutionSource().isBlank() || task.targetSkillCodes()==null || !task.targetSkillCodes().contains(task.skillCode()) || task.prerequisiteSkillCodes()==null) throw new InvalidGeneratedContentException();
    if(count("select count(*) from skills where code=?",task.skillCode())==0) throw new InvalidGeneratedContentException();
    for(String target:task.targetSkillCodes()) if(count("select count(*) from skills where code=?",target)==0) throw new InvalidGeneratedContentException();
    for(String prerequisite:task.prerequisiteSkillCodes()) if(count("select count(*) from skills where code=?",prerequisite)==0) throw new InvalidGeneratedContentException();
    if(!codeRunner.configured()) throw new LlmUnavailableException("Piston is required to validate generated content");
    var validation=codeRunner.run(task.referenceSolutionSource(),task.testSource());
    if(!validation.passed()) throw new InvalidGeneratedContentException();
    db.update("insert into tasks(skill_code,title,statement,starter_code,test_source,test_file_name) values(?,?,?,?,?,?)",task.skillCode(),task.title(),task.statement(),task.starterCode()==null?"":task.starterCode(),task.testSource(),task.testFileName());
    long taskId=db.queryForObject("select last_insert_rowid()",Long.class);
    for(String target:new LinkedHashSet<>(task.targetSkillCodes())) db.update("insert into task_target_skills(task_id,skill_code) values(?,?)",taskId,target);
    for(String prerequisite:new LinkedHashSet<>(task.prerequisiteSkillCodes())) db.update("insert into task_prerequisite_skills(task_id,skill_code) values(?,?)",taskId,prerequisite);
  }

  @PostMapping("/attempts") @Transactional public ResponseEntity<?> attempt(@RequestBody Map<String,Object> body,HttpServletRequest r){long u=student(r);var l=active(u);if(l==null)throw bad("NO_ACTIVE_LESSON","Сначала начните урок");long task=((Number)body.get("taskId")).longValue();if(count("select count(*) from lesson_tasks where lesson_id=? and task_id=?",l.get("id"),task)==0)throw bad("TASK_NOT_IN_LESSON","Задача не назначена этому уроку"); String source=(String)body.get("sourceCode"); if(!codeRunner.status().available()) return ResponseEntity.status(503).body(Map.of("error","RUNNER_UNAVAILABLE","message","Java runtime Piston недоступен","runner",runner()));var taskRow=db.queryForMap("select test_source from tasks where id=?",task);var result=codeRunner.run(source,(String)taskRow.get("test_source"));db.update("insert into submissions(lesson_id,task_id,source_code,passed,runner_output) values(?,?,?,?,?)",l.get("id"),task,source,result.passed()?1:0,result.output());long submissionId=db.queryForObject("select last_insert_rowid()",Long.class);if(result.passed()&&db.update("insert or ignore into successful_task_credit(user_id,task_id) values(?,?)",u,task)>0)for(var target:db.queryForList("select skill_code from task_target_skills where task_id=?",task))credit(u,(String)target.get("skill_code"),((Number)l.get("id")).longValue(),((Number)l.get("number")).intValue());return ResponseEntity.ok(Map.of("id",submissionId,"passed",result.passed(),"output",result.output(),"progress",progress(u))); }
  @GetMapping("/progress") public Map<String,Object> progress(HttpServletRequest r){return Map.of("skills",progress(uid(r)));}
  @GetMapping("/chat") public Map<String,Object> chat(HttpServletRequest r){var l=active(uid(r));return Map.of("messages",l==null?List.of():db.queryForList("select id,role,content,created_at as createdAt from chat_messages where lesson_id=? order by id",l.get("id")),"llm",llm(uid(r)));}
  @PostMapping("/chat") public ResponseEntity<?> sendChat(@RequestBody Map<String,String> body,HttpServletRequest r){long u=student(r);var l=active(u);if(l==null)throw bad("NO_ACTIVE_LESSON","Сначала начните урок");String question=body.get("content");db.update("insert into chat_messages(lesson_id,role,content) values(?,?,?)",l.get("id"),"STUDENT",question);try {String answer=tutor.reply(u,tutorContext(u,l),question);db.update("insert into chat_messages(lesson_id,role,content) values(?,?,?)",l.get("id"),"ASSISTANT",answer);long id=db.queryForObject("select last_insert_rowid()",Long.class);return ResponseEntity.ok(Map.of("message",Map.of("id",id,"role","ASSISTANT","content",answer,"createdAt",Instant.now().toString()),"llm",llm(u)));}catch(LlmUnavailableException e){return ResponseEntity.status(503).body(Map.of("error","LLM_UNAVAILABLE","message",e.getMessage(),"llm",llm(u)));}}

  @PostMapping("/admin/students") public Map<String,Object> createStudent(@RequestBody Map<String,Object>b,HttpServletRequest r){admin(r);String login=(String)b.get("login"),password=(String)b.get("password"),name=(String)b.get("displayName");if(login==null||password==null||name==null)throw bad("INVALID_STUDENT","Нужны login, password, displayName");boolean enabled=!Boolean.FALSE.equals(b.get("llmEnabled"));db.update("insert into users(login,password_hash,role,display_name,llm_enabled) values(?,?,?,?,?)",login,passwords.encode(password),"STUDENT",name,enabled?1:0);return db.queryForMap("select id,login,role,display_name as displayName,llm_enabled as llmEnabled from users where login=?",login);}
  @GetMapping("/admin/students") public Map<String,Object> students(HttpServletRequest r){admin(r);return Map.of("students",db.queryForList("select id,login,display_name as displayName,llm_enabled as llmEnabled,created_at as createdAt from users where role='STUDENT' order by id"));}
  @PatchMapping("/admin/llm") public Map<String,Object> globalLlm(@RequestBody Map<String,Boolean>b,HttpServletRequest r){admin(r);db.update("update app_settings set value=? where key='llm_enabled'",Boolean.TRUE.equals(b.get("enabled"))?"true":"false");return Map.of("enabled",Boolean.TRUE.equals(b.get("enabled")));}
  @PatchMapping("/admin/students/{id}/llm") public Map<String,Object> studentLlm(@PathVariable long id,@RequestBody Map<String,Boolean>b,HttpServletRequest r){admin(r);db.update("update users set llm_enabled=? where id=? and role='STUDENT'",Boolean.TRUE.equals(b.get("enabled"))?1:0,id);return Map.of("id",id,"enabled",Boolean.TRUE.equals(b.get("enabled")));}
  @GetMapping("/admin/students/{id}") public Map<String,Object> student(@PathVariable long id,HttpServletRequest r){admin(r);var s=db.queryForMap("select id,login,display_name as displayName,llm_enabled as llmEnabled from users where id=? and role='STUDENT'",id);return Map.of("student",s,"progress",progress(id),"llm",llm(id));}
  @GetMapping("/admin/students/{id}/lessons") public Map<String,Object> lessons(@PathVariable long id,HttpServletRequest r){admin(r);return Map.of("lessons",db.queryForList("select id,lesson_number as number,started_at as startedAt,finished_at as finishedAt from lessons where user_id=? order by lesson_number",id));}
  @GetMapping("/admin/students/{id}/lessons/{lessonId}") public Map<String,Object> lessonDetail(@PathVariable long id,@PathVariable long lessonId,HttpServletRequest r){admin(r);var l=db.queryForMap("select id,lesson_number as number,started_at as startedAt,finished_at as finishedAt from lessons where id=? and user_id=?",lessonId,id);var tasks=db.queryForList("select t.id,t.title,t.statement from tasks t join lesson_tasks x on x.task_id=t.id where x.lesson_id=?",lessonId);for(var t:tasks)t.put("submissions",db.queryForList("select id,source_code as sourceCode,passed,runner_output as output,created_at as createdAt from submissions where lesson_id=? and task_id=? order by id",lessonId,t.get("id")));return Map.of("lesson",l,"chat",db.queryForList("select id,role,content,created_at as createdAt from chat_messages where lesson_id=? order by id",lessonId),"tasks",tasks);}

  private TutorContext tutorContext(long userId,Map<String,Object> lesson) { long lessonId=((Number)lesson.get("id")).longValue(); var taskRows=db.queryForList("select t.id,t.title,t.statement,ts.skill_code from lesson_tasks lt join tasks t on t.id=lt.task_id join task_target_skills ts on ts.task_id=t.id where lt.lesson_id=? order by t.id desc limit 1",lessonId); String skillCode=null,skillTitle=null; Long taskId=null;String taskTitle=null,taskStatement=null,source=null,output=null;Boolean passed=null; if(!taskRows.isEmpty()){var task=taskRows.getFirst();taskId=((Number)task.get("id")).longValue();taskTitle=(String)task.get("title");taskStatement=(String)task.get("statement");skillCode=(String)task.get("skill_code");var titleRows=db.queryForList("select title from skills where code=?",skillCode);skillTitle=titleRows.isEmpty()?skillCode:(String)titleRows.getFirst().get("title");var submission=db.queryForList("select source_code,passed,runner_output from submissions where lesson_id=? and task_id=? order by id desc limit 1",lessonId,taskId);if(!submission.isEmpty()){var last=submission.getFirst();source=(String)last.get("source_code");passed=((Number)last.get("passed")).intValue()==1;output=(String)last.get("runner_output");}} return new TutorContext(lessonId,((Number)lesson.get("number")).intValue(),skillCode,skillTitle,taskId,taskTitle,taskStatement,source,passed,output); }
  private Map<String,Object> status(Map<String,Object> u){return Map.of("user",viewUser(u),"llm",llm(((Number)u.get("id")).longValue()),"runner",runner());} private Map<String,Object> viewUser(Map<String,Object> u){return Map.of("id",u.get("id"),"login",u.get("login"),"role",u.get("role"),"displayName",u.get("display_name"),"llmEnabled",u.get("llm_enabled"));}
  private Map<String,Object> llm(long id){return tutor.status(id).asMap();} private Map<String,Object> runner(){var state=codeRunner.status();return obj("available",state.available(),"reason",state.reason(),"javaVersion",state.javaVersion());}
  private List<Map<String,Object>> progress(long u){return db.queryForList("select s.code as skillCode,s.title,coalesce(x.completed_iterations,0) as completedIterations,coalesce(x.iteration_successes,0) as iterationSuccesses,coalesce(x.mastered,0) as mastered from skills s left join student_skills x on x.skill_code=s.code and x.user_id=? order by s.sort_order",u);}
  private void credit(long user,String skill,long lessonId,int lessonNumber){db.update("insert or ignore into student_skills(user_id,skill_code) values(?,?)",user,skill);int successes=count("select count(distinct c.task_id) from successful_task_credit c join task_target_skills ts on ts.task_id=c.task_id join submissions s on s.task_id=c.task_id and s.lesson_id=? and s.passed=1 where c.user_id=? and ts.skill_code=?",lessonId,user,skill);if(successes<3){db.update("update student_skills set iteration_successes=? where user_id=? and skill_code=?",successes,user,skill);return;}var x=db.queryForMap("select completed_iterations,first_iteration_lesson_number from student_skills where user_id=? and skill_code=?",user,skill);int completed=((Number)x.get("completed_iterations")).intValue();Integer first=x.get("first_iteration_lesson_number")==null?null:((Number)x.get("first_iteration_lesson_number")).intValue();boolean due=completed==0||(completed==1&&lessonNumber==first+1)||(completed==2&&lessonNumber==first+3);if(!due||count("select count(*) from skill_iterations where user_id=? and skill_code=? and lesson_id=?",user,skill,lessonId)>0)return;int done=completed+1;db.update("insert into skill_iterations(user_id,skill_code,iteration_number,lesson_id) values(?,?,?,?)",user,skill,done,lessonId);db.update("update student_skills set completed_iterations=?,iteration_successes=0,first_iteration_lesson_number=case when first_iteration_lesson_number is null then ? else first_iteration_lesson_number end,mastered=? where user_id=? and skill_code=?",done,lessonNumber,done>=3?1:0,user,skill);}
  private Map<String,Object> nextSkill(long userId,int lessonNumber,long lessonId) {
    int startBlock=db.queryForObject("select starting_block from student_languages where user_id=?",Integer.class,userId);
    var rows=db.queryForList("select s.code,s.title,s.block_no,coalesce(x.completed_iterations,0) completed,coalesce(x.first_iteration_lesson_number,0) first from skills s left join student_skills x on x.skill_code=s.code and x.user_id=? where coalesce(x.mastered,0)=0 and s.block_no>=? and (s.prerequisite_code is null or exists(select 1 from student_skills p where p.user_id=? and p.skill_code=s.prerequisite_code and p.mastered=1)) order by s.block_no,s.sort_order",userId,startBlock,userId);
    var due=new ArrayList<Map<String,Object>>();
    for(var row:rows) { int completed=((Number)row.get("completed")).intValue(), first=((Number)row.get("first")).intValue(); if(completed==0||(completed==1&&lessonNumber==first+1)||(completed==2&&lessonNumber==first+3)) due.add(row); }
    if(due.isEmpty()) return null;
    var withBank=new ArrayList<Map<String,Object>>();
    for(var row:due) if(count("select count(*) from tasks t join task_target_skills ts on ts.task_id=t.id where t.active=1 and ts.skill_code=? and not exists(select 1 from successful_task_credit c where c.user_id=? and c.task_id=t.id) and not exists(select 1 from lesson_tasks x where x.lesson_id=? and x.task_id=t.id)",row.get("code"),userId,lessonId)>0) withBank.add(row);
    var candidates=withBank.isEmpty()?due:withBank;
    int earliest=candidates.stream().mapToInt(x->((Number)x.get("block_no")).intValue()).min().orElseThrow();
    candidates.removeIf(x->((Number)x.get("block_no")).intValue()!=earliest);
    Collections.shuffle(candidates); var selected=candidates.getFirst();
    return Map.of("code",selected.get("code"),"title",selected.get("title"),"blockNo",selected.get("block_no"));
  }
  private Map<String,Object> active(long u){var x=db.queryForList("select id,lesson_number as number,started_at as startedAt from lessons where user_id=? and finished_at is null order by id desc",u);return x.isEmpty()?null:x.getFirst();} private Map<String,Object> lesson(long id){return db.queryForMap("select id,lesson_number as number,started_at as startedAt,finished_at as finishedAt from lessons where id=?",id);} private void requireDiagnostic(long u){if(count("select count(*) from student_languages where user_id=? and diagnostic_completed_at is not null",u)==0)throw bad("DIAGNOSTIC_REQUIRED","Сначала пройдите диагностику");} private int count(String q,Object...p){return db.queryForObject(q,Integer.class,p);} private long uid(HttpServletRequest r){return ((Number)user(r).get("id")).longValue();} @SuppressWarnings("unchecked") private Map<String,Object> user(HttpServletRequest r){return (Map<String,Object>)r.getAttribute("user");} private long student(HttpServletRequest r){if(!"STUDENT".equals(user(r).get("role")))throw bad("FORBIDDEN","Нужна роль STUDENT");return uid(r);} private void admin(HttpServletRequest r){if(!"ADMIN".equals(user(r).get("role")))throw bad("FORBIDDEN","Нужна роль ADMIN");} private Optional<String> cookie(HttpServletRequest r){return r.getCookies()==null?Optional.empty():Arrays.stream(r.getCookies()).filter(c->c.getName().equals("adaptive_session")).map(Cookie::getValue).findFirst();} private String randomToken(){byte[] b=new byte[32];new SecureRandom().nextBytes(b);return Base64.getUrlEncoder().withoutPadding().encodeToString(b);} private Object json(Object value){try{return new com.fasterxml.jackson.databind.ObjectMapper().readValue((String)value,List.class);}catch(Exception e){throw new IllegalStateException(e);}} private Map<String,Object> obj(Object... entries){var m=new LinkedHashMap<String,Object>();for(int i=0;i<entries.length;i+=2)m.put((String)entries[i],entries[i+1]);return m;} private ApiError bad(String c,String m){return new ApiError(c,m);}
}
@ResponseStatus(HttpStatus.BAD_REQUEST) class ApiError extends RuntimeException { final String code; ApiError(String c,String m){super(m);code=c;} }
class InvalidGeneratedContentException extends RuntimeException { }
@RestControllerAdvice class Errors { @ExceptionHandler(ApiError.class) ResponseEntity<?> api(ApiError e){return ResponseEntity.badRequest().body(Map.of("error",e.code,"message",e.getMessage()));} }
