-- Tasks inside one iteration go from warm-up (1) to a small combined task (3).
-- NULL marks legacy bank tasks generated before difficulty existed.
ALTER TABLE tasks ADD COLUMN difficulty INTEGER;
-- Explanations generated by an older prompt are regenerated when the LLM is available.
ALTER TABLE explanations ADD COLUMN prompt_version INTEGER NOT NULL DEFAULT 1;
